[package]
name = "n2s"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
axum = "0.8.3"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] }
